-- Parte 2: Crear la nueva BDD en Microsoft SQL Server con todas sus tablas, columnas y relaciones. Generar dentro del
--Gestor el Diagrama de la BDD

CREATE TABLE ORIGEN (
                ID_ORIGEN INT NOT NULL,
                ORIGEN VARCHAR(30) NOT NULL,
                CONSTRAINT ID_ORIGEN PRIMARY KEY (ID_ORIGEN)
)

CREATE TABLE USUARIO_CREADOR (
                ID_USUARIO_CREADOR VARCHAR(20) NOT NULL,
                NOMBRE_USUARIO VARCHAR(50) NOT NULL,
                ID_ORIGEN INT NOT NULL,
                CONSTRAINT ID_USUARIO_CREADOR PRIMARY KEY (ID_USUARIO_CREADOR)
)

CREATE TABLE MEDICO_TRATANTE (
                ID_MED_TRAT INT NOT NULL,
                NOMBRE_MEDICO_TRATANTE VARCHAR(100) NOT NULL,
                USUARIO_CONTROL VARCHAR(20) NOT NULL,
                CONSTRAINT ID_MED_TRAT PRIMARY KEY (ID_MED_TRAT)
)

CREATE TABLE AFILIADO (
                HCL INT NOT NULL,
                NOMBRE_APELLIDOS VARCHAR(150) NOT NULL,
                CEDULA VARCHAR(10) NOT NULL,
                TELF_1 VARCHAR(20) NOT NULL,
                TELF_2 VARCHAR(20) NOT NULL,
                CONSTRAINT HCL PRIMARY KEY (HCL)
)

CREATE TABLE ESTADO (
                ID_ESTADO INT NOT NULL,
                ESTADO VARCHAR(20) NOT NULL,
                CONSTRAINT ID_ESTADO PRIMARY KEY (ID_ESTADO)
)

CREATE TABLE NIVEL (
                ID_NIVEL INT NOT NULL,
                NIVEL VARCHAR(10) NOT NULL,
                CONSTRAINT ID_NIVEL PRIMARY KEY (ID_NIVEL)
)

CREATE TABLE ESPECIALIDAD (
                ID_ESPECIALIDAD INT NOT NULL,
                NOMBRE_ESPECIALIDAD VARCHAR(30) NOT NULL,
                ID_NIVEL INT NOT NULL,
                CONSTRAINT ID_ESPECIALIDAD PRIMARY KEY (ID_ESPECIALIDAD)
)

CREATE TABLE CITA (
                ID_CITA INT NOT NULL,
                FECHA DATETIME NOT NULL,
                HORA_CITA DATETIME NOT NULL,
                HORA_ATENCION DATETIME NOT NULL,
                MINUTOS INT NOT NULL,
                ID_ESPECIALIDAD INT NOT NULL,
                ID_ESTADO INT NOT NULL,
                HCL INT NOT NULL,
                ID_MED_TRAT INT NOT NULL,
                ID_USUARIO_CREADOR VARCHAR(20) NOT NULL,
                CONSTRAINT ID_CITA PRIMARY KEY (ID_CITA)
)

ALTER TABLE USUARIO_CREADOR ADD CONSTRAINT ORIGEN_USUARIO_CREADOR_fk
FOREIGN KEY (ID_ORIGEN)
REFERENCES ORIGEN (ID_ORIGEN)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CITA ADD CONSTRAINT USUARIO_CREADOR_CITA_fk
FOREIGN KEY (ID_USUARIO_CREADOR)
REFERENCES USUARIO_CREADOR (ID_USUARIO_CREADOR)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CITA ADD CONSTRAINT MEDICO_TRATANTE_CITA_fk
FOREIGN KEY (ID_MED_TRAT)
REFERENCES MEDICO_TRATANTE (ID_MED_TRAT)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CITA ADD CONSTRAINT AFILIADO_CITA_fk
FOREIGN KEY (HCL)
REFERENCES AFILIADO (HCL)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CITA ADD CONSTRAINT ESTADO_CITA_fk
FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADO (ID_ESTADO)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE ESPECIALIDAD ADD CONSTRAINT NIVEL_ESPECIALIDAD_fk
FOREIGN KEY (ID_NIVEL)
REFERENCES NIVEL (ID_NIVEL)
ON DELETE NO ACTION
ON UPDATE NO ACTION

ALTER TABLE CITA ADD CONSTRAINT ESPECIALIDAD_CITA_fk
FOREIGN KEY (ID_ESPECIALIDAD)
REFERENCES ESPECIALIDAD (ID_ESPECIALIDAD)
ON DELETE NO ACTION
ON UPDATE NO ACTION


--